command: ["streamlit", "run", "app/main.py"]

env:
  - name: DATABRICKS_HOST
    valueFrom:
      secretRef:
        scope: my_app_scope
        key: DATABRICKS_HOST
  - name: DATABRICKS_HTTP
    valueFrom:
      secretRef:
        scope: my_app_scope
        key: DATABRICKS_HTTP
  - name: DATABRICKS_TOKEN
    valueFrom:
      secretRef:
        scope: my_app_scope
        key: DATABRICKS_TOKEN